/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManualsSlugRouteImport } from './routes/manuals.$slug'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/_superadmin'
import { Route as ApiPublicBootstrapRouteImport } from './routes/api/public/bootstrap'
import { Route as AuthenticatedSettingsTemplatesRouteImport } from './routes/_authenticated/settings.templates'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedSettingsErpRouteImport } from './routes/_authenticated/settings.erp'
import { Route as AuthenticatedSettingsBomExclusionsRouteImport } from './routes/_authenticated/settings.bom-exclusions'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products.$productId'
import { Route as AuthenticatedSuperadminAdminUsersRouteImport } from './routes/_authenticated/_superadmin.admin.users'
import { Route as AuthenticatedSuperadminAdminOrgsRouteImport } from './routes/_authenticated/_superadmin.admin.orgs'
import { Route as AuthenticatedSuperadminAdminAuditRouteImport } from './routes/_authenticated/_superadmin.admin.audit'
import { Route as AuthenticatedSuperadminAdminOrgsOrgIdRouteImport } from './routes/_authenticated/_superadmin.admin.orgs.$orgId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualsSlugRoute = ManualsSlugRouteImport.update({
  id: '/manuals/$slug',
  path: '/manuals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/_superadmin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBootstrapRoute = ApiPublicBootstrapRouteImport.update({
  id: '/api/public/bootstrap',
  path: '/api/public/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsTemplatesRoute =
  AuthenticatedSettingsTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsErpRoute =
  AuthenticatedSettingsErpRouteImport.update({
    id: '/erp',
    path: '/erp',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBomExclusionsRoute =
  AuthenticatedSettingsBomExclusionsRouteImport.update({
    id: '/bom-exclusions',
    path: '/bom-exclusions',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedSuperadminAdminUsersRoute =
  AuthenticatedSuperadminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminAdminOrgsRoute =
  AuthenticatedSuperadminAdminOrgsRouteImport.update({
    id: '/admin/orgs',
    path: '/admin/orgs',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminAdminAuditRoute =
  AuthenticatedSuperadminAdminAuditRouteImport.update({
    id: '/admin/audit',
    path: '/admin/audit',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminAdminOrgsOrgIdRoute =
  AuthenticatedSuperadminAdminOrgsOrgIdRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => AuthenticatedSuperadminAdminOrgsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/reset': typeof AuthResetRoute
  '/manuals/$slug': typeof ManualsSlugRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/settings/bom-exclusions': typeof AuthenticatedSettingsBomExclusionsRoute
  '/settings/erp': typeof AuthenticatedSettingsErpRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/admin/audit': typeof AuthenticatedSuperadminAdminAuditRoute
  '/admin/orgs': typeof AuthenticatedSuperadminAdminOrgsRouteWithChildren
  '/admin/users': typeof AuthenticatedSuperadminAdminUsersRoute
  '/admin/orgs/$orgId': typeof AuthenticatedSuperadminAdminOrgsOrgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/reset': typeof AuthResetRoute
  '/manuals/$slug': typeof ManualsSlugRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/settings/bom-exclusions': typeof AuthenticatedSettingsBomExclusionsRoute
  '/settings/erp': typeof AuthenticatedSettingsErpRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/admin/audit': typeof AuthenticatedSuperadminAdminAuditRoute
  '/admin/orgs': typeof AuthenticatedSuperadminAdminOrgsRouteWithChildren
  '/admin/users': typeof AuthenticatedSuperadminAdminUsersRoute
  '/admin/orgs/$orgId': typeof AuthenticatedSuperadminAdminOrgsOrgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/_superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/auth/reset': typeof AuthResetRoute
  '/manuals/$slug': typeof ManualsSlugRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/settings/bom-exclusions': typeof AuthenticatedSettingsBomExclusionsRoute
  '/_authenticated/settings/erp': typeof AuthenticatedSettingsErpRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/settings/templates': typeof AuthenticatedSettingsTemplatesRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/_authenticated/_superadmin/admin/audit': typeof AuthenticatedSuperadminAdminAuditRoute
  '/_authenticated/_superadmin/admin/orgs': typeof AuthenticatedSuperadminAdminOrgsRouteWithChildren
  '/_authenticated/_superadmin/admin/users': typeof AuthenticatedSuperadminAdminUsersRoute
  '/_authenticated/_superadmin/admin/orgs/$orgId': typeof AuthenticatedSuperadminAdminOrgsOrgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/dashboard'
    | '/products'
    | '/settings'
    | '/auth/reset'
    | '/manuals/$slug'
    | '/products/$productId'
    | '/settings/bom-exclusions'
    | '/settings/erp'
    | '/settings/team'
    | '/settings/templates'
    | '/api/public/bootstrap'
    | '/admin/audit'
    | '/admin/orgs'
    | '/admin/users'
    | '/admin/orgs/$orgId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/dashboard'
    | '/products'
    | '/settings'
    | '/auth/reset'
    | '/manuals/$slug'
    | '/products/$productId'
    | '/settings/bom-exclusions'
    | '/settings/erp'
    | '/settings/team'
    | '/settings/templates'
    | '/api/public/bootstrap'
    | '/admin/audit'
    | '/admin/orgs'
    | '/admin/users'
    | '/admin/orgs/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_superadmin'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/products'
    | '/_authenticated/settings'
    | '/auth/reset'
    | '/manuals/$slug'
    | '/_authenticated/products/$productId'
    | '/_authenticated/settings/bom-exclusions'
    | '/_authenticated/settings/erp'
    | '/_authenticated/settings/team'
    | '/_authenticated/settings/templates'
    | '/api/public/bootstrap'
    | '/_authenticated/_superadmin/admin/audit'
    | '/_authenticated/_superadmin/admin/orgs'
    | '/_authenticated/_superadmin/admin/users'
    | '/_authenticated/_superadmin/admin/orgs/$orgId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ManualsSlugRoute: typeof ManualsSlugRoute
  ApiPublicBootstrapRoute: typeof ApiPublicBootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuals/$slug': {
      id: '/manuals/$slug'
      path: '/manuals/$slug'
      fullPath: '/manuals/$slug'
      preLoaderRoute: typeof ManualsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_superadmin': {
      id: '/_authenticated/_superadmin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap': {
      id: '/api/public/bootstrap'
      path: '/api/public/bootstrap'
      fullPath: '/api/public/bootstrap'
      preLoaderRoute: typeof ApiPublicBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/templates': {
      id: '/_authenticated/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof AuthenticatedSettingsTemplatesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/erp': {
      id: '/_authenticated/settings/erp'
      path: '/erp'
      fullPath: '/settings/erp'
      preLoaderRoute: typeof AuthenticatedSettingsErpRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/bom-exclusions': {
      id: '/_authenticated/settings/bom-exclusions'
      path: '/bom-exclusions'
      fullPath: '/settings/bom-exclusions'
      preLoaderRoute: typeof AuthenticatedSettingsBomExclusionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/_superadmin/admin/users': {
      id: '/_authenticated/_superadmin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/_superadmin/admin/orgs': {
      id: '/_authenticated/_superadmin/admin/orgs'
      path: '/admin/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminOrgsRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/_superadmin/admin/audit': {
      id: '/_authenticated/_superadmin/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminAuditRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/_superadmin/admin/orgs/$orgId': {
      id: '/_authenticated/_superadmin/admin/orgs/$orgId'
      path: '/$orgId'
      fullPath: '/admin/orgs/$orgId'
      preLoaderRoute: typeof AuthenticatedSuperadminAdminOrgsOrgIdRouteImport
      parentRoute: typeof AuthenticatedSuperadminAdminOrgsRoute
    }
  }
}

interface AuthenticatedSuperadminAdminOrgsRouteChildren {
  AuthenticatedSuperadminAdminOrgsOrgIdRoute: typeof AuthenticatedSuperadminAdminOrgsOrgIdRoute
}

const AuthenticatedSuperadminAdminOrgsRouteChildren: AuthenticatedSuperadminAdminOrgsRouteChildren =
  {
    AuthenticatedSuperadminAdminOrgsOrgIdRoute:
      AuthenticatedSuperadminAdminOrgsOrgIdRoute,
  }

const AuthenticatedSuperadminAdminOrgsRouteWithChildren =
  AuthenticatedSuperadminAdminOrgsRoute._addFileChildren(
    AuthenticatedSuperadminAdminOrgsRouteChildren,
  )

interface AuthenticatedSuperadminRouteChildren {
  AuthenticatedSuperadminAdminAuditRoute: typeof AuthenticatedSuperadminAdminAuditRoute
  AuthenticatedSuperadminAdminOrgsRoute: typeof AuthenticatedSuperadminAdminOrgsRouteWithChildren
  AuthenticatedSuperadminAdminUsersRoute: typeof AuthenticatedSuperadminAdminUsersRoute
}

const AuthenticatedSuperadminRouteChildren: AuthenticatedSuperadminRouteChildren =
  {
    AuthenticatedSuperadminAdminAuditRoute:
      AuthenticatedSuperadminAdminAuditRoute,
    AuthenticatedSuperadminAdminOrgsRoute:
      AuthenticatedSuperadminAdminOrgsRouteWithChildren,
    AuthenticatedSuperadminAdminUsersRoute:
      AuthenticatedSuperadminAdminUsersRoute,
  }

const AuthenticatedSuperadminRouteWithChildren =
  AuthenticatedSuperadminRoute._addFileChildren(
    AuthenticatedSuperadminRouteChildren,
  )

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBomExclusionsRoute: typeof AuthenticatedSettingsBomExclusionsRoute
  AuthenticatedSettingsErpRoute: typeof AuthenticatedSettingsErpRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSettingsTemplatesRoute: typeof AuthenticatedSettingsTemplatesRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBomExclusionsRoute:
    AuthenticatedSettingsBomExclusionsRoute,
  AuthenticatedSettingsErpRoute: AuthenticatedSettingsErpRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSettingsTemplatesRoute: AuthenticatedSettingsTemplatesRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ManualsSlugRoute: ManualsSlugRoute,
  ApiPublicBootstrapRoute: ApiPublicBootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
